### ISSUE TITLE
Retry a step that uses actions built in script method?

### ISSUE THREAD

**Issue by chris-hinds** [nick-fields/retry#102]
I have a step that runs a JS script using Actions built in script method.

Can this sort of step work with this retry action?

e.g.

```
- name: Step Name
        uses: actions/github-script@v6
        with:
          script: |
            const test = require(`./test-script.js`)
            await test({ github, context, core })
```

**Comment by nick-fields** [comment]
This action only supports running scripts, not other actions (which is what actions/github-script@v6 is, and not actually a built in feature).  

To achieve what you want, you could just wrap your command in a node script command like `node -e "<your node code here>"`.  It won't be pretty, but it will work.
