### ISSUE TITLE
`set-output` and `save-state` are deprecated

### ISSUE THREAD

**Issue by muffl0n** [nick-fields/retry#103]
**Describe the bug**
Since runner version 2.298.2 `set-output` and `save-state` are deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Expected behavior**
No deprecation message

**Screenshots**
n/a

**Logs**
n/a

**Comment by itsankit-google** [comment]
+1. This action is being used in an important workflow of our repo and we are also observing this warning.
