### ISSUE TITLE
Upgrade to Node 20

### ISSUE THREAD

**Issue by prichey** [nick-fields/retry#125]
I'm getting the following warning in annotations:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: nick-fields/retry@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

Edit: I have a PR which upgrades the action / repo to support Node 20 here https://github.com/nick-fields/retry/pull/126

**Comment by nick-fields** [comment]
Thanks again! See https://github.com/marketplace/actions/retry-step?version=v3.0.0
